export type eBidStatus = 'Draft' | 'Published' | 'Submission Open' | 'Submission Closed' | 'Bids Opened' | 'Under Evaluation' | 'Awarded' | 'Cancelled';
export type EvalGateStage = 'preliminary' | 'technical' | 'commercial' | 'financial';
export type EvalGateStatus = 'locked' | 'not_started' | 'in_progress' | 'completed';
export type VendorGateResult = 'pending' | 'pass' | 'fail' | 'eliminated' | 'recommended';

export interface EvalCriteria { id: string; name: string; description: string; type: 'boolean' | 'score'; weight: number; required: boolean; }
export interface VendorCriteriaEval { criteriaId: string; passed?: boolean; score?: number; notes?: string; }
export interface VendorGateEval { vendorId: string; vendorName: string; criteriaEvals: VendorCriteriaEval[]; weightedScore?: number; result: VendorGateResult; evaluatorNotes?: string; evaluatedBy?: string; evaluatedDate?: string; }
export interface EvalGate { stage: EvalGateStage; label: string; status: EvalGateStatus; passingScore?: number; vendorEvals: VendorGateEval[]; startedDate?: string; completedDate?: string; completedBy?: string; gateNotes?: string; }
export interface eBidLineItem { id: string; code: string; description: string; quantity: number; unit: string; specifications: string; estimatedUnitPrice?: number; }
export interface eBidVendorInvitation { id: string; vendorId: string; vendorName: string; email: string; contactPerson: string; phone: string; invitedDate: string; status: 'Invited' | 'Acknowledged' | 'Submitted' | 'Declined' | 'Disqualified'; acknowledgedDate?: string; submittedDate?: string; declineReason?: string; submissionId?: string; }
export interface eBidSubmissionLineItem { lineItemId: string; code: string; description: string; quantity: number; unit: string; unitPrice: number; totalPrice: number; deliveryDays: number; remarks?: string; }
export interface eBidSubmission { id: string; submissionRef: string; eBidId: string; vendorId: string; vendorName: string; submittedDate: string; revisedDate?: string; status: 'Submitted' | 'Revised' | 'Withdrawn' | 'Disqualified' | 'Shortlisted' | 'Awarded'; totalAmount: number; currencyCode: string; paymentTerms: string; deliveryDays: number; validityDays: number; bidBondProvided: boolean; bidBondAmount?: number; lineItems: eBidSubmissionLineItem[]; technicalScore?: number; commercialScore?: number; overallScore?: number; evaluatorNotes?: string; attachments: { name: string; size: string }[]; }
export interface eBid { id: string; eBidNumber: string; title: string; linkedRFQId: string; linkedRFQNumber: string; linkedPRId: string; linkedPRNumber: string; status: eBidStatus; bidType: 'Open' | 'Sealed' | 'Reverse Auction'; category: string; department: string; createdBy: string; createdDate: string; publishedDate?: string; submissionOpenDate: string; submissionDeadline: string; bidOpeningDate: string; awardDate?: string; bidValidityDays: number; bidBondRequired: boolean; bidBondAmount?: number; estimatedValue: number; currency: string; description: string; termsAndConditions: string[]; lineItems: eBidLineItem[]; vendorInvitations: eBidVendorInvitation[]; submissions: eBidSubmission[]; awardedVendorId?: string; awardedVendorName?: string; awardedAmount?: number; awardedDate?: string; awardNotes?: string; activities: { action: string; user: string; timestamp: string; type: string }[]; gates?: EvalGate[]; }
